baseURL = "nabakshirak.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "The Journey"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Kharis Kaban"
author = "Kharis Kaban"
description = "Security Engineer"
profilePicture = "images/Photo.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/khariskaban/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/nabakshirak"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/khariskaban"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:khariskaban@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"